//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub type GetSpend {
  GetSpend(id: String, amount_in_cent: Int, name: Option(String))
}

pub fn get_spend(id id: String) {
  let sql = "SELECT id, amount_in_cent, name FROM session WHERE id = ? LIMIT 1"
  #(sql, [dev.ParamString(id)], get_spend_decoder())
}

pub fn get_spend_decoder() -> decode.Decoder(GetSpend) {
  use id <- decode.field(0, decode.string)
  use amount_in_cent <- decode.field(1, decode.int)
  use name <- decode.field(2, decode.optional(decode.string))
  decode.success(GetSpend(id:, amount_in_cent:, name:))
}

pub type GetSpends {
  GetSpends(id: String, amount_in_cent: Int, name: Option(String))
}

pub fn get_spends() {
  let sql = "SELECT id, amount_in_cent, name FROM session"
  #(sql, [], get_spends_decoder())
}

pub fn get_spends_decoder() -> decode.Decoder(GetSpends) {
  use id <- decode.field(0, decode.string)
  use amount_in_cent <- decode.field(1, decode.int)
  use name <- decode.field(2, decode.optional(decode.string))
  decode.success(GetSpends(id:, amount_in_cent:, name:))
}

pub type CreateSpend {
  CreateSpend(id: String, amount_in_cent: Int, name: Option(String))
}

pub fn create_spend(
  id id: String,
  amount_in_cent amount_in_cent: Int,
  name name: Option(String),
) {
  let sql =
    "INSERT INTO session (
 id,
 amount_in_cent,
 name
) VALUES (?, ?, ?) RETURNING id, amount_in_cent, name"
  #(
    sql,
    [
      dev.ParamString(id),
      dev.ParamInt(amount_in_cent),
      dev.ParamNullable(option.map(name, fn(v) { dev.ParamString(v) })),
    ],
    create_spend_decoder(),
  )
}

pub fn create_spend_decoder() -> decode.Decoder(CreateSpend) {
  use id <- decode.field(0, decode.string)
  use amount_in_cent <- decode.field(1, decode.int)
  use name <- decode.field(2, decode.optional(decode.string))
  decode.success(CreateSpend(id:, amount_in_cent:, name:))
}

pub fn new_pledge(
  id id: String,
  session_id session_id: String,
  amount_in_cent amount_in_cent: Int,
  participant_name participant_name: Option(String),
) {
  let sql =
    "INSERT INTO participation (
  id ,
  session_id ,
  amount_in_cent,
  participant_name)
 VALUES (?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamString(session_id),
    dev.ParamInt(amount_in_cent),
    dev.ParamNullable(
      option.map(participant_name, fn(v) { dev.ParamString(v) }),
    ),
  ])
}

pub type GetPledges {
  GetPledges(
    id: String,
    session_id: String,
    amount_in_cent: Int,
    participant_name: Option(String),
  )
}

pub fn get_pledges(session_id session_id: String) {
  let sql =
    "SELECT id, session_id, amount_in_cent, participant_name FROM participation p  WHERE p.session_id = ?"
  #(sql, [dev.ParamString(session_id)], get_pledges_decoder())
}

pub fn get_pledges_decoder() -> decode.Decoder(GetPledges) {
  use id <- decode.field(0, decode.string)
  use session_id <- decode.field(1, decode.string)
  use amount_in_cent <- decode.field(2, decode.int)
  use participant_name <- decode.field(3, decode.optional(decode.string))
  decode.success(GetPledges(
    id:,
    session_id:,
    amount_in_cent:,
    participant_name:,
  ))
}
